ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}
# RUN mkdir -p /usr/temp
# COPY shared/output.txt /usr/
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
